spring:
  application:
    name: federation-jvm-spring-example
server:
  port: 4004
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter:  debug
