---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "products"
  namespace: "default"
  labels:
    app: "products"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "products"
  template:
    metadata:
      labels:
        app: "products"
    spec:
      containers:
      - name: "products"
        image: "us.gcr.io/vuclip-personalization-dev/products:v5"
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 700m
            memory: 1536Mi
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "products-hpa"
  namespace: "default"
  labels:
    app: "products"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "products"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
